//logica de las vistas
import React, { useState } from 'react';
import { View, Text, ScrollView, Switch, TextInput, Pressable } from 'react-native';
import { C, styles } from '../constants/theme';
import type { Screen, ProScreen } from '../types';
import { Title, Card, Button, Brand, Ring, Macro, Setting, Stat, Field, MobileHeader, MobileNav } from '../components';

const meals = [['DESAYUNO','650 kcal','Avena con proteína...'], /* ... resto de tus meals ... */] as const;
const proNav: [ProScreen,string][] = [['pro-dashboard','PANEL PRINCIPAL'],['users','USUARIOS'],['plans','PLANES'],['reports','REPORTES']];

export function Welcome({go}:{go:(s:Screen)=>void}) { return <View style={styles.welcome}><View style={styles.welcomeGlow}/><Brand/><Text style={styles.welcomeTitle}>TU NUTRICIÓN,{`\n`}EN MOVIMIENTO.</Text><Text style={styles.lead}>Seguimiento de macros, escáner de alimentos y hábitos que se sostienen.</Text><Button label="COMENZAR" onPress={()=>go('dashboard')}/><Pressable onPress={()=>go('pro-dashboard')}><Text style={styles.proLink}>ACCESO PROFESIONAL</Text></Pressable></View>; }
export function Dashboard({go,consumed}:{go:(s:Screen)=>void;consumed:number}) { return <><MobileHeader onProfile={()=>go('profile')} onSettings={()=>go('settings')}/><ScrollView contentContainerStyle={styles.mobileContent}><Text style={styles.eyebrow}>HOY</Text><Title dark>BUEN DÍA, CARLOS</Title><View style={styles.rings}><Ring value={consumed} label="kcal"/><Ring value={2200-consumed} label="RESTANTES"/></View><Title>MACROS</Title><Macro label="PROTEÍNA" now="120" goal="160g" percent={75}/><Macro label="CARBS" now="200" goal="250g" percent={80}/><Macro label="FATS" now="45" goal="65g" percent={69}/><Card><Text style={styles.cardLabel}>PRÓXIMA COMIDA</Text><Text style={styles.cardTitle}>ALMUERZO · 950 KCAL</Text><Text style={styles.body}>Pechuga de pollo, arroz integral, brócoli y aceite de oliva.</Text></Card></ScrollView><MobileNav screen="dashboard" setScreen={go}/></>; }
export function Scanner({go,onScan}:{go:(s:Screen)=>void;onScan:()=>void}) { const [manual,setManual]=useState(''); return <><MobileHeader onProfile={()=>go('profile')} onSettings={()=>go('settings')}/><ScrollView contentContainerStyle={styles.mobileContent}><Title dark>SCANNER</Title><Card style={styles.viewfinder}><Text style={styles.viewfinderText}>POSITION BARCODE{`\n`}IN FRAME</Text><View style={styles.target}/></Card><Text style={styles.cardLabel}>INGRESO MANUAL</Text><TextInput value={manual} onChangeText={setManual} placeholder="Nombre del alimento" placeholderTextColor={C.dim} style={styles.input}/><Button label="AGREGAR ALIMENTO" onPress={()=>{setManual('');onScan();go('dashboard')}}/><Title>RECENT SCANS</Title><Card><Text style={styles.cardTitle}>PANCITO DE MOLDE</Text><Text style={styles.body}>30G SCOOP · 120 KCAL</Text></Card></ScrollView><MobileNav screen="scanner" setScreen={go}/></>; }
export function Calendar({go}:{go:(s:Screen)=>void}) { return <><MobileHeader onProfile={()=>go('profile')} onSettings={()=>go('settings')}/><ScrollView contentContainerStyle={styles.mobileContent}><Title dark>CALENDARIO</Title><View style={styles.week}>{['LUN 13','MAR 14','MIÉ 15','JUE 16','VIE 17','SÁB 18','DOM 19'].map((d,i)=><View key={d} style={[styles.day,i===2&&styles.dayActive]}><Text style={styles.dayText}>{d}</Text></View>)}</View><Title>CONSUMO DIARIO</Title><Card><Text style={styles.cardLabel}>ÚLTIMOS 7 DÍAS · META: 2200 KCAL</Text><View style={styles.chart}>{[70,88,75,92,80,60,85].map((h,i)=><View key={i} style={[styles.chartBar,{height:h}]} />)}</View></Card><Title>RESUMEN MENSUAL</Title><View style={styles.statGrid}><Stat label="PROMEDIO DIARIO" value="1,950 kcal"/><Stat label="DÍAS EN META" value="18/30"/><Stat label="MEJOR RACHA" value="7 días"/></View></ScrollView><MobileNav screen="calendar" setScreen={go}/></>; }
export function Profile({go}:{go:(s:Screen)=>void}) { return <><MobileHeader onProfile={()=>go('profile')} onSettings={()=>go('settings')}/><ScrollView contentContainerStyle={styles.mobileContent}><Card style={{alignItems:'center'}}><View style={[styles.avatar,styles.avatarLarge]}><Text style={styles.avatarText}>CM</Text></View><Title dark>CARLOS MÉNDEZ</Title><Text style={styles.body}>carlos@email.com</Text></Card><Title>MI META DIARIA</Title><Card><Text style={styles.bigNumber}>84% COMPLETADO</Text><Text style={styles.body}>2200 / 2200 KCAL</Text></Card><Title>ESTADÍSTICAS CLAVE</Title><View style={styles.statGrid}><Stat label="PESO ACTUAL" value="78 KG"/><Stat label="PESO META" value="72 KG"/><Stat label="ACTIVIDAD" value="MODERADO"/></View><Button label="EDITAR PERFIL" onPress={()=>go('settings')} ghost/></ScrollView><MobileNav screen="profile" setScreen={go}/></>; }
export function Settings({go}:{go:(s:Screen)=>void}) { const [dark,setDark]=useState(true),[push,setPush]=useState(true); return <><MobileHeader onProfile={()=>go('profile')} onSettings={()=>go('settings')}/><ScrollView contentContainerStyle={styles.mobileContent}><Title dark>CONFIGURACIÓN</Title><Text style={styles.cardLabel}>APARIENCIA</Text><Setting label="MODO OSCURO / CLARO" right={<Switch value={dark} onValueChange={setDark} trackColor={{true:C.lime}}/>}/><Text style={styles.cardLabel}>PREFERENCIAS</Text><Setting label="NOTIFICACIONES PUSH" right={<Switch value={push} onValueChange={setPush} trackColor={{true:C.lime}}/>}/><Setting label="UNIDADES DE MEDIDA" value="MÉTRICO (KG)"/><Setting label="IDIOMA" value="Español"/><Card><Text style={styles.cardTitle}>NUTRITRACK PRO</Text><Text style={styles.body}>v2.4.1{`\n\n`}Desarrollado bajo estándares urbanos industriales de alto rendimiento.</Text></Card></ScrollView><MobileNav screen="settings" setScreen={go}/></>; }
export function ProShell({screen,go,children}:{screen:ProScreen;go:(s:Screen)=>void;children:React.ReactNode}) { return <View style={styles.pro}><View style={styles.sidebar}><View><Brand/>{proNav.map(([id,label])=><Pressable key={id} onPress={()=>go(id)} style={[styles.sideItem,screen===id&&styles.sideActive]}><Text style={[styles.sideText,screen===id&&styles.sideTextActive]}>{label}</Text></Pressable>)}</View><Card><Text style={styles.cardTitle}>Luis G. Silvestre</Text><Text style={styles.cardLabel}>NUTRICIONISTA ÉLITE</Text></Card></View><View style={styles.proMain}><View style={styles.topbar}><Text style={styles.topbarText}>{proNav.find(x=>x[0]===screen)?.[1]}</Text><TextInput placeholder="Buscar paciente, plan, reporte..." placeholderTextColor={C.dim} style={styles.search}/></View><ScrollView contentContainerStyle={styles.proContent}>{children}</ScrollView></View></View>; }
export function ProDashboard({go}:{go:(s:Screen)=>void}) { return <ProShell screen="pro-dashboard" go={go}><Title>VISTA GENERAL</Title><Text style={styles.body}>Control operativo de la cohorte activa.</Text><View style={styles.proGrid}><Stat label="PACIENTES ACTIVOS" value="1,492"/><Stat label="ADHERENCIA PROMEDIO" value="84.5%"/><Stat label="PLANES EN ALERTA" value="12"/></View><Card><Title dark>TENDENCIAS DE ADHERENCIA</Title><View style={styles.chart}>{[45,62,55,80,70,92,84,96].map((h,i)=><View key={i} style={[styles.chartBar,{height:h}]} />)}</View></Card><Card><Title dark>ACTIVIDAD RECIENTE</Title>{['Jackson M. completó su registro de hoy','Sarah Miller subió adherencia a 92%','Chen L. requiere revisión de protocolo'].map(t=><Text key={t} style={styles.listLine}>{t}</Text>)}</Card></ProShell>; }
export function Users({go}:{go:(s:Screen)=>void}) { return <ProShell screen="users" go={go}><View style={styles.row}><View><Title>DIRECTORIO DE PACIENTES</Title><Text style={styles.body}>Consulte, filtre y gestione todos los expedientes activos.</Text></View><Button label="+ NUEVO PROTOCOLO" onPress={()=>go('plans')}/></View><View style={styles.proGrid}><Stat label="TOTAL ACTIVOS" value="142"/><Stat label="ALTO RIESGO" value="12"/></View><Card>{[['Doe John','PT-8832','Desviado','49% Crítico'],['Miller Sarah','PT-9104','En Ruta','92% Óptimo'],['Jackson Robert','PT-7741','Monitoreando','78% Aceptable']].map(p=><View key={p[1]} style={styles.tableRow}><View><Text style={styles.cardTitle}>{p[0]}</Text><Text style={styles.body}>ID: {p[1]}</Text></View><Text style={styles.body}>{p[2]}</Text><Text style={styles.tableValue}>{p[3]}</Text></View>)}</Card></ProShell>; }
export function Plans({go}:{go:(s:Screen)=>void}) { const [saved,setSaved]=useState(false); return <ProShell screen="plans" go={go}><View style={styles.row}><View><Title>GESTIÓN DE PLANES ALIMENTICIOS</Title><Text style={styles.body}>Creación y asignación de pautas nutricionales personalizadas.</Text></View><View style={styles.row}><Button label={saved?'PLAN GUARDADO':'GUARDAR PLAN'} onPress={()=>setSaved(true)} ghost/><Button label="ASIGNAR A PACIENTE" onPress={()=>setSaved(true)}/></View></View><Card><View style={styles.fields}><Field label="SELECCIONAR PACIENTE" value="JACKSON, M. (HYPERTROPHY)"/><Field label="CALORÍAS OBJETIVO (KCAL)" value="2800"/><Field label="DISTRIBUCIÓN MACROS" value="35% / 45% / 20%"/></View></Card><View style={styles.split}><Card style={styles.flex}><View style={styles.row}><Title dark>CONSTRUCTOR DE DIETAS</Title><Button label="AÑADIR" onPress={()=>{}}/></View>{meals.map(m=><View key={m[0]} style={styles.meal}><View style={styles.row}><Text style={styles.mealTitle}>{m[0]}</Text><Text style={styles.body}>{m[1]}</Text></View><Text style={styles.body}>{m[2]}</Text></View>)}</Card><Card style={styles.activePlans}><Title dark>PLANES ACTIVOS</Title>{['PROTOCOLO HIPERTROFIA V2','DEFINICIÓN EXTREMA FASE 2','MANTENIMIENTO GENERAL'].map((p,i)=><View key={p} style={[styles.meal,i===1&&styles.alert]}><Text style={[styles.mealTitle,i===1&&{color:C.red}]}>{p}</Text><Text style={styles.body}>Asignado a paciente · {i===1?'2100':'3200'} kcal</Text></View>)}</Card></View></ProShell>; }
export function Reports({go}:{go:(s:Screen)=>void}) { return <ProShell screen="reports" go={go}><View style={styles.row}><View><Title>ANALÍTICAS DEL SISTEMA</Title><Text style={styles.body}>Estadísticas consolidadas de adherencia y deficiencias.</Text></View><Button label="GENERAR PDF SEMANAL" onPress={()=>{}}/></View><Card><Title dark>TENDENCIAS DE ADHERENCIA DE LA COHORTE</Title><View style={styles.chart}>{[55,63,70,72,78,83,85,91].map((h,i)=><View key={i} style={[styles.chartBar,{height:h}]} />)}</View></Card><View style={styles.proGrid}><Stat label="PACIENTES ACTIVOS" value="1,492"/><Stat label="CUMPLIMIENTO PROTOCOLO" value="84.5%"/></View><Card><Title dark>DEFICIENCIAS COMUNES EN COHORTE</Title>{[['Vitamina D3','68%'],['Magnesio','45%'],['Omega 3','32%']].map(([n,v])=><Macro key={n} label={n.toUpperCase()} now={v} goal="" percent={parseInt(v)}/>)}</Card></ProShell>; }
